// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RedisEshop.Entities;
using System;

namespace RedisEshop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20170816160151_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RedisEshop.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Added");

                    b.Property<string>("Description");

                    b.Property<string>("Identifier");

                    b.Property<int>("Likes");

                    b.Property<decimal>("Price");

                    b.Property<int?>("TagId");

                    b.Property<string>("Title");

                    b.Property<int>("Views");

                    b.HasKey("ProductId");

                    b.HasIndex("TagId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RedisEshop.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Identifier");

                    b.Property<int?>("ProductId");

                    b.Property<string>("Title");

                    b.HasKey("TagId");

                    b.HasIndex("ProductId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("RedisEshop.Entities.Product", b =>
                {
                    b.HasOne("RedisEshop.Entities.Tag")
                        .WithMany("Products")
                        .HasForeignKey("TagId");
                });

            modelBuilder.Entity("RedisEshop.Entities.Tag", b =>
                {
                    b.HasOne("RedisEshop.Entities.Product")
                        .WithMany("Tags")
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
